/* ============================================================
   TECHZICK — AI Sentinel Threat Intelligence Data
   Add new threats at the TOP of this array (newest first).
   The blog section auto-renders the latest 4 entries.
   ============================================================ */

const THREATS = [
  {
    id: 'zionsiphon-water-treatment-malware-2026',
    date: '2026-04-17',
    title: 'ZionSiphon — Malware Built to Sabotage Water Treatment Systems',
    type: 'Nation-State',
    severity: 'CRITICAL',
    excerpt: 'Newly discovered OT malware ZionSiphon targets water treatment and desalination plants, capable of raising chlorine levels to dangerous concentrations and manipulating hydraulic pressures. Propagates via USB. Darktrace researchers found a logic flaw preventing execution — but warn a fixed variant could be weaponised imminently.',
    tags: ['Critical Infrastructure', 'OT/ICS', 'CRITICAL'],
    anchor: 'zionsiphon-2026',
  },
  {
    id: 'microsoft-patch-tuesday-april-2026',
    date: '2026-04-14',
    title: 'Microsoft April 2026 Patch Tuesday — 167 Flaws Fixed, 2 Zero-Days Including Exploited SharePoint Bug',
    type: 'Zero-Day',
    severity: 'CRITICAL',
    excerpt: 'Microsoft patched 167 vulnerabilities including 8 Critical flaws and 2 zero-days. A SharePoint Server spoofing vulnerability was actively exploited in the wild. Office RCE bugs triggerable via preview pane and a Defender privilege escalation to SYSTEM also patched. Immediate patching required.',
    tags: ['Zero-Day', 'Microsoft', 'Patch Tuesday'],
    anchor: 'ms-patch-tuesday-april-2026',
  },
  {
    id: 'mcp-tool-poisoning-cve-2026-2241',
    date: '2026-04-16',
    title: 'MCP Tool Poisoning — CVE-2026-2241 Exploited Across 3,000+ AI Agent Deployments',
    type: 'AI/LLM Attack',
    severity: 'CRITICAL',
    excerpt: 'Critical vulnerability in the MCP tool-call response parser allows malicious servers to inject hidden instructions into AI agent context windows. Actively exploited to exfiltrate API keys and cloud credentials from agentic CI/CD pipelines. CISA KEV listed.',
    tags: ['AI Security', 'MCP', 'CRITICAL'],
    anchor: 'mcp-tool-poisoning-2026',
  },
  {
    id: 'oracle-cloud-breach-april-2026',
    date: '2026-04-13',
    title: 'Oracle Cloud Identity Breach — 6M Enterprise Tenant Credentials Exposed',
    type: 'Data Breach',
    severity: 'CRITICAL',
    excerpt: 'Oracle confirmed unauthorised access to its Identity Cloud Service affecting approximately 6 million enterprise tenant records including SSO tokens, hashed passwords, and SAML signing certificates. Threat actor listed data on BreachForums.',
    tags: ['Data Breach', 'Cloud', 'CRITICAL'],
    anchor: 'oracle-cloud-breach-2026',
  },
  {
    id: 'scattered-spider-telecom-april-2026',
    date: '2026-04-09',
    title: 'Scattered Spider Returns — SIM-Swap Campaign Targets 14 US Financial Institutions',
    type: 'Nation-State',
    severity: 'HIGH',
    excerpt: 'Scattered Spider threat group launched a coordinated SIM-swap and social engineering campaign against 14 US financial institutions, bypassing MFA on privileged admin accounts. $22M in fraudulent wire transfers confirmed. FBI issuing alerts.',
    tags: ['Social Engineering', 'Finance', 'HIGH'],
    anchor: 'scattered-spider-april-2026',
  },
  {
    id: 'windows-clfs-zerodday-cve-2026-29824',
    date: '2026-04-08',
    title: 'Windows CLFS Zero-Day — CVE-2026-29824 Under Active Exploitation (CVSS 8.8)',
    type: 'Zero-Day',
    severity: 'HIGH',
    excerpt: 'Microsoft disclosed a privilege escalation zero-day in the Windows Common Log File System driver actively exploited by ransomware affiliates for SYSTEM-level access. Patch released in April Patch Tuesday — 900,000+ unpatched endpoints estimated.',
    tags: ['Zero-Day', 'Windows', 'HIGH'],
    anchor: 'windows-clfs-zerodday-2026',
  },
  {
    id: 'nightlock-2026',
    date: '2026-04-02',
    title: 'NightLock Ransomware — 47 Hospitals Hit in 72 Hours',
    type: 'Ransomware',
    severity: 'HIGH',
    excerpt: 'Coordinated ransomware on 47 healthcare organisations across North America and Europe. Combined $50M ransom demand with threat to expose 3.8M patient records. HHS and FDA emergency response activated.',
    tags: ['Ransomware', 'Healthcare', 'HIGH'],
    anchor: 'nightlock-2026',
  },
  {
    id: 'nist-csf-21-2026',
    date: '2026-04-01',
    title: 'NIST CSF 2.1 — AI Risk Controls Now Mandatory for Federal Contractors',
    type: 'Compliance',
    severity: 'HIGH',
    excerpt: 'NIST officially released Cybersecurity Framework 2.1 with a new Governance function and expanded AI/ML risk controls. AI governance frameworks are now mandatory for federal contractors. SOC 2 auditors updating AI control mappings.',
    tags: ['Compliance', 'NIST', 'AI Security'],
    anchor: 'nist-csf-21-2026',
  },
  {
    id: 'chrome-zerodday-cve-2026-1847',
    date: '2026-03-21',
    title: 'Critical Chrome Zero-Day — CVE-2026-1847 (CVSS 9.4)',
    type: 'Zero-Day',
    severity: 'CRITICAL',
    excerpt: 'Critical zero-day in Chrome\'s V8 engine actively exploited by state-sponsored actors targeting financial institutions. RCE via malicious web pages — no user interaction required. Google issued emergency patch.',
    tags: ['Zero-Day', 'Browser', 'CRITICAL'],
    anchor: 'chrome-zerodday-2026',
  },
  {
    id: 'ai-rls-misconfiguration-cve-2025-48757',
    date: '2026-03-12',
    title: 'CVE-2025-48757 — 170+ AI-Generated Apps Shipped Without Row-Level Security',
    type: 'Zero-Day',
    severity: 'CRITICAL',
    excerpt: '170+ apps built via AI coding platforms shipped without RLS enabled on Supabase backends. One instance exposed 13,000 users\' PII. Password reset tokens accessible to anonymous users — full account takeover demonstrated.',
    tags: ['Zero-Day', 'AI Security', 'CRITICAL'],
    anchor: 'ai-rls-misconfiguration-2026',
  },
  {
    id: 'copilot-echoleak-2026',
    date: '2026-03-05',
    title: 'Microsoft Copilot EchoLeak — Zero-Click Prompt Injection',
    type: 'AI/LLM Attack',
    severity: 'CRITICAL',
    excerpt: 'Zero-click prompt injection in M365 Copilot silently exfiltrated documents from OneDrive, SharePoint, and Teams via trusted Microsoft domains. No user action required. $200M+ estimated business impact in Q1 2026.',
    tags: ['AI Security', 'Microsoft 365', 'CRITICAL'],
    anchor: 'copilot-echoleak-2026',
  },
  {
    id: 'ai-model-poisoning-finance-2026',
    date: '2026-02-25',
    title: 'AI Model Poisoning — Backdoored LLMs Deployed by 3 Major Banks',
    type: 'AI/LLM Attack',
    severity: 'HIGH',
    excerpt: 'Backdoored fine-tuned LLMs distributed via Hugging Face targeted financial institutions\' fraud detection models. Poisoned models introduced systematic blind spots for specific fraud patterns. Estimated $180M in undetected fraud.',
    tags: ['AI Security', 'Finance', 'Supply Chain'],
    anchor: 'ai-model-poisoning-2026',
  },
  {
    id: 'india-blocks-supabase-2026',
    date: '2026-02-18',
    title: 'India Blocks Supabase Under Section 69A — Thousands of Apps Down Overnight',
    type: 'Regulatory',
    severity: 'HIGH',
    excerpt: 'Indian government ordered ISPs to block Supabase under Section 69A of the IT Act. Production apps relying on Supabase broke overnight. $100M+ estimated economic impact on SaaS ecosystem.',
    tags: ['Regulatory', 'SaaS', 'Geopolitical'],
    anchor: 'india-blocks-supabase-2026',
  },
  {
    id: 'supabase-mcp-dataleak-2026',
    date: '2026-02-10',
    title: 'Supabase MCP Data Leak — Prompt Injection via AI Agent Dumps Entire Database',
    type: 'AI/LLM Attack',
    severity: 'HIGH',
    excerpt: 'Prompt injection via support ticket tricked an AI agent (Cursor + MCP) into dumping an entire Supabase SQL database — including OAuth tokens. service_role key bypassed all row-level security.',
    tags: ['AI Security', 'Prompt Injection', 'MCP'],
    anchor: 'supabase-mcp-dataleak-2026',
  },
  {
    id: 'nationalid-breach-2026',
    date: '2026-01-22',
    title: 'NationalID Breach — 2.1 Billion Records Leaked (Largest Ever)',
    type: 'Data Breach',
    severity: 'CRITICAL',
    excerpt: 'The largest data breach in history: SSNs, biometric hashes, passport data, and financial history for 2.1 billion individuals exposed. Data appeared on darknet forums immediately. FTC emergency response activated globally.',
    tags: ['Data Breach', 'Identity', 'CRITICAL'],
    anchor: 'nationalid-breach-2026',
  },
  {
    id: 'gridstrike-volt-typhoon-2026',
    date: '2026-01-07',
    title: 'GridStrike — Volt Typhoon Pre-Positions in 6 US Power Grid Utilities',
    type: 'Nation-State',
    severity: 'CRITICAL',
    excerpt: 'CISA and FBI confirmed Volt Typhoon successfully pre-positioned malware inside OT systems of 6 US regional power utilities. No disruption triggered — assessed as pre-positioning for future conflict escalation.',
    tags: ['Nation-State', 'Critical Infrastructure', 'CRITICAL'],
    anchor: 'gridstrike-2026',
  },
  {
    id: 'skybridge-lockbit4-2025',
    date: '2025-12-11',
    title: 'LockBit 4.0 — SkyBridge Casino Group Ransomware Across 18 Properties',
    type: 'Ransomware',
    severity: 'HIGH',
    excerpt: 'LockBit 4.0 encrypted SkyBridge Casino Group\'s operations across 18 properties in 3 countries. $40M ransom demand, 11M customer records exposed, 5-day operational outage.',
    tags: ['Ransomware', 'Gaming', 'HIGH'],
    anchor: 'skybridge-lockbit4-2025',
  },
  {
    id: 'exchange-zerodday-cve-2025-49742',
    date: '2025-12-04',
    title: 'Microsoft Exchange Zero-Day — CVE-2025-49742 (CVSS 9.1) Exploited in Wild',
    type: 'Zero-Day',
    severity: 'HIGH',
    excerpt: 'Critical SSRF-to-RCE chain in Microsoft Exchange exploited by multiple threat actors. Unauthenticated RCE. Estimated 35,000+ Exchange servers compromised before patching. CISA Emergency Directive ED-25-08 issued.',
    tags: ['Zero-Day', 'Microsoft Exchange', 'HIGH'],
    anchor: 'exchange-zerodday-2025',
  },
  {
    id: 'npm-supply-chain-node-oauth2-proxy-2025',
    date: '2025-11-19',
    title: 'npm Supply Chain Attack — "node-oauth2-proxy" Reverse Shell in 180K Downloads',
    type: 'Supply Chain',
    severity: 'CRITICAL',
    excerpt: 'Malicious versions of the widely-used npm package node-oauth2-proxy contained a reverse shell payload. Downloaded 180,000+ times before detection. Thousands of CI/CD pipelines exposed; credential theft from build environments.',
    tags: ['Supply Chain', 'npm', 'CRITICAL'],
    anchor: 'npm-supply-chain-2025',
  },
  {
    id: 'medchain-ransomware-2025',
    date: '2025-11-03',
    title: 'MedChain Ransomware — 230 Hospitals Offline, 12 Deaths Linked to Disruption',
    type: 'Ransomware',
    severity: 'CRITICAL',
    excerpt: 'VenomSec ransomware encrypted patient records across 230 hospitals. $95M ransom demand, 4.2M patient records at risk. 12 patient deaths linked to care disruption. HHS investigation launched.',
    tags: ['Ransomware', 'Healthcare', 'CRITICAL'],
    anchor: 'medchain-ransomware-2025',
  },
  {
    id: 'fortinet-forti-os-zerodday-cve-2025-32756',
    date: '2025-10-15',
    title: 'Fortinet FortiOS Zero-Day — CVE-2025-32756 (CVSS 9.6) Exploited Before Patch',
    type: 'Zero-Day',
    severity: 'CRITICAL',
    excerpt: 'Critical RCE in FortiOS SSL-VPN actively exploited in the wild before patch availability. Attackers deployed custom malware implants. Thousands of unpatched FortiGate devices compromised; several government agencies affected.',
    tags: ['Zero-Day', 'Fortinet', 'CRITICAL'],
    anchor: 'fortinet-forti-os-zerodday-2025',
  },
  {
    id: 'salt-typhoon-telecom-2025',
    date: '2025-10-08',
    title: 'Salt Typhoon — 9 US Telecom Carriers Compromised by China APT',
    type: 'Nation-State',
    severity: 'CRITICAL',
    excerpt: 'US intelligence confirmed Salt Typhoon penetrated 9 major telecom carriers and intercepted US lawful wiretap (CALEA) infrastructure. AT&T and Verizon confirmed victims. Senate Intelligence Committee convened emergency briefings.',
    tags: ['Nation-State', 'Telecom', 'CRITICAL'],
    anchor: 'salt-typhoon-2025',
  },
];
